export type CSVProperty = {
  BEHIND_HOME: number;
  BEHIND_AWAY: number;
  CLR_BU: number;
  CLR_CSB: number;
  CLR_TI: number;
  EFFORT_SPOIL: number;
  FK_AGAINST: number;
  FK_FOR: number;
  GOAL_HOME: number;
  GOAL_AWAY: number;
  HB_EF: number;
  HB_IE: number;
  HB_TO: number;
  I50_INDIVIDUAL: number;
  KICK_EF: number;
  KICK_IE: number;
  KICK_TO: number;
  MARK_CONT: number;
  MARK_F50: number;
  MARK_INT: number;
  MARK_UC: number;
  POSS_CONT: number;
  POSS_HB_REC: number;
  POSS_UNCON: number;
  RUCK_HO: number;
  TACKLE_EF: number;
};
